export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESSED = 'REGISTER_SUCCESSED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
// Product
export const PRODUCT = 'PRODUCT';
export const FETCH_PRODUCT_SUCCEEDED = 'FETCH_PRODUCT_SUCCEEDED';
export const FETCH_PRODUCT_FAILED='FETCH_PRODUCT_FAILED';
export const SEARCH = 'SEARCH';

// order
export const ORDER = 'ORDERS';
export const FETCH_SUCCEEDED_ORDER = 'FETCH_SUCCEEDED_ORDER';
export const FETCH_FAILED_ORDER = 'ETCH_FAILED_ORDER';
